<?php /* Smarty version 2.6.26, created on 2016-06-29 12:26:32
         compiled from includes/finaliza.tpl */ ?>
<?php echo '<div id="footer"><!--<div id="seguinos_footer"><p>Seguinos en:</p><img src="img/facebook-icon.png" height="30" width="30" alt=""><img src="img/twitter-icon.png" height="30" width="30" alt=""><img src="img/rss-icon.png" height="30" width="30" alt=""></div>--><div class="center-boxing" style="background: url(css/footer-bg.gif); height:100px;"><p class="copyright">&reg;2013 www.solo-loft.com.ar<br />Todos los derechos reservados.<br />Telefonos: +54 (011) 15-4415-9559 / +54 (011) 4713-2567<br />Buenos Aires - Argentina<br />info@solo-loft.com.ar</p><a href="http://www.70artstudio.com" target="_blank" title="70\' ART STUDIO"><div id="woodstockdg"></div></a></div><!--<div class="center-boxing" style="height: 60px; margin-top: 50px; width: 460px; margin-left: 250px;"><span  class=\'st_linkedin_hcount\' displayText=\'LinkedIn\'></span><span  class=\'st_twitter_hcount\' displayText=\'Tweet\'></span><span  class=\'st_facebook_hcount\' displayText=\'Facebook\'></span><span  class=\'st_fblike_hcount\' ></span><span  class=\'st_plusone_hcount\' ></span></div>--></div></div></div><script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"></script><script type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['SITE_PATH']; ?><?php echo 'js/modernizr.2.0.min.js"></script><script type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['SITE_PATH']; ?><?php echo 'js/jquery.wipetouch.js"></script><script type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['SITE_PATH']; ?><?php echo 'js/mediaelement-and-player.js"></script><script type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['SITE_PATH']; ?><?php echo 'js/home-page.js"></script>'; ?><?php echo '
        <script type="text/javascript">
            homeCarousel.init();
        </script>
		<script type="text/javascript">var switchTo5x=false;</script><script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script><script type="text/javascript">stLight.options({publisher:\'03254927-0657-4919-8b25-44d5a3f46c5a\'});</script>
        '; ?><?php echo ''; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "includes/analytics.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '</body></html>'; ?>